version: 2

jobs:
  release:
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/meinto/glow
    steps:
      - checkout
      - run:
          name: Setup packr
          command: |
            mkdir ../packr
            cd ../packr 
            curl -SLO https://github.com/gobuffalo/packr/releases/download/v2.7.1/packr_2.7.1_linux_amd64.tar.gz
            tar -xzf packr_2.7.1_linux_amd64.tar.gz
            cd ../glow
      - run: curl -sL https://git.io/goreleaser | bash
  #     - persist_to_workspace:
  #         root: .
  #         paths:
  #           - "dist"
  # snap:
  #   docker:
  #     - image: cibuilds/snapcraft:stable
  #   steps:
  #     - checkout
  #     - attach_workspace:
  #         at: .
  #     - run: snapcraft
  #     - run:
  #         name: Publish to store
  #         command: |
  #           # The Snapcraft login file here will expire March 1st, 2022. A new one will need to be created then.
  #           mkdir .snapcraft
  #           echo $SNAPCRAFT_LOGIN_FILE | base64 --decode --ignore-garbage > .snapcraft/snapcraft.cfg
  #           snapcraft push *.snap --release stable

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*$/
      # - snap:
      #     filters:
      #       branches:
      #         ignore: /.*/
      #       tags:
      #         only: /^v.*$/
      #     requires:
      #       - release